name: Test commit
on:
  push:
    # Sequence of patterns matched against refs/tags asd 
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # Push events to matching *, i.e. 20.15.10
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Get sha
        id: br
        run: echo "::set-output name=sha::$(git rev-list -n 1 ${{github.ref}})"
      - name: Get branches for sha
        id: cond
        run: |
          echo "$(git branch --points-at ${{ steps.br.outputs.sha }})"
          echo "::set-output name=branch::$(git branch --points-at ${{ steps.br.outputs.sha }})" 
      - name: Set tag output
        id: vars
        run: |
          echo "${{ steps.cond.outputs.branch }}"
          echo ::set-output name=last_tag::${{github.ref_name}}

      - name: Update Changelog
        if: contains(steps.cond.outputs.branch, 'main')  
        run: |
          curl -o git-chglog.tar.gz -L https://github.com/git-chglog/git-chglog/releases/download/v0.15.1/git-chglog_0.15.1_linux_amd64.tar.gz
          tar -xvzf git-chglog.tar.gz
          chmod u+x git-chglog
          ./git-chglog -o new_tag_changelog.md ${{ steps.vars.outputs.last_tag }}
          mv CHANGELOG.md old_changelog.md
          cat new_tag_changelog.md old_changelog.md > CHANGELOG.md
          rm git-chglog
          rm new_tag_changelog.md
          rm old_changelog.md
      - name: Commit new changelog
        if: contains(steps.cond.outputs.branch, 'main')  
        run: |
          git add CHANGELOG.md
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "docs: Updated CHANGELOG for ${{ steps.vars.outputs.last_tag }} "
          git push origin main
