name: Test commit
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # Push events to matching *, i.e. 20.15.10
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Get Branch
        run: |
           raw=$(git branch -r --contains ${{ github.ref }})
           branch=${raw/origin\/}
           echo ::set-env name=BRANCH::$branch
      - run: echo ${{ env.BRANCH }}

      - name: Set tag output
        id: vars
        run: echo ::set-output name=last_tag::${{github.ref_name}}

      - name: Update Changelog
        run: |
           echo >> test.txt
      - name: Commit new changelog
        run: |
          echo ${{github.base_ref}}
          git add test.txt
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "docs: Updated CHANGELOG for ${{ steps.vars.outputs.last_tag }} "
          git push origin main
